version: "3"

services:
  backend:
    # image: backend
    build: ./backend
    command:
      npm run dev
      # context: ./backend
      # dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./backend/.env.backend:/surveyvore/.env:rw
      - ./backend/src:/surveyvore/src:rw
      - ./backend/node_modules:/surveyvore/node_modules
      - ./backend/package.json:/surveyvore/package.json:rw
      - ./backend/migrations:/surveyvore/migrations:rw
      - ./backend/jest.config.js:/surveyvore/jest.config.js:rw
      - ./backend/tsconfig.json:/surveyvore/tsconfig.json
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
    volumes:
      - ./frontend/public:/surveyvoreApp/public:rw
      - ./frontend/src:/surveyvoreApp/src:rw
      - ./frontend/package.json:/surveyvoreApp/package.json:rw
      - ./frontend/node_modules:/surveyvoreApp/node_modules

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=surveyvore
      - POSTGRES_USER=surveyvore
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/customDataFolder
    volumes:
      - ./dbData:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U surveyvore -d surveyvore"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

