version: "3"

services:
  backend:
    image: cyrilleaquilina/surveyvore-backend:latest
    env_file: .env.backend
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: cyrilleaquilina/surveyvore-frontend:latest

  db:
    image: postgres
    restart: always
    volumes:
      - ./dbData:/var/lib/postgresql/data/customDataFolder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d surveyvore -U surveyvore"]
      interval: 5s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:1.21.3
    depends_on:
      - frontend
      - backend
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx

